application: cooper-rover
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /iframe
  static_dir: iframe
	
- url: /.*
  script: main.app
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest